# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 1

[[main]]
  name = "Key Info"
  url = "#info"
  weight = 2

[[main]]
  name = "RSVP"
  url = "#rsvp"
  weight = 3

[[main]]
  name = "Gallery"
  url = "#gallery"
  weight = 4

[[main]]
  name = "Accommodation"
  url = "#accommodation"
  weight = 5

[[main]]
  name = "Location"
  url = "#location"
  weight = 6
